name: Bug Report
description: File a bug report
title: "[BUG]: your bug report title"
labels: "maybe: bug"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a description of the bug that occurred."
    validations:
      require: true
  - type: input
    id: code-version
    attributes:
      label: Code Version
      #description:
      placeholder: eg. v1.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using the code on?
      #description:
      options:
        - Windows 11
        - Windows 10
        - Other
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using the code in?
      #description:
      options:
        - Brave
        - Google Chrome
        - Mozilla Firefox
        - Opera
        - Safari
        - Vivaldi
        - Other
    validations:
      required: true
  - type: textarea
    id: bug-steps
    attributes:
      label: Steps until the bug appears
      description: "[optional] You can add the steps taken to be able to reproduce your problem."
      placeholder: "1. Description of step 1 ...
      2. Description of step 2 ...
      ..."
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: "[optional] You can add what is the expected result."
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "[optional] You may add screenshots to further explain your problem."
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "[optional] You may provide additional context for us to better understand how this issue occured."
