name: Translates
description: Improve code translation
title: "[TRANSLATE] Your title"
labels: "translate"
body:
  - type: input
    id: language
    attributes:
      label: Language
      #description:
      placeholder: eg. english
    validations:
      required: true
  - type: input
    id: lang-code
    attributes:
      label: Language code
      description: "You can find the language code at: [List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)"
      placeholder: eg. en
  - type: textarea
    id: translate
    attributes:
      label: Translate YAML
      description: "You can send the YAML file already translated or write it in this section.\n\n[WARNING] If you want to directly write the translation in this section, the code must start with **```yaml** and end with ```. You can use the \"Preview\" tab to see if the code has been written correctly.\n\nYou can use as a template: [en.yaml](https://github.com/BrowserSourcesForOBS/obs-timer-controller/blob/main/core/translates/en.yaml)"
      placeholder: "```yaml\nhome:\n\tclose: Close the window and stop the code\n\tcronoTitle: CLOCKS\n\tcdownTitle: TIMERS\n\tcdowntimeTitle: TIME UNTIL...\n\ttwitchextTitle: EXTENSIBLE TWITCH\n\ttimeTitle: CURRENT TIME\n\tnotycopycrono: URL copied to clipboard\ncrono:\n\tbuttons:\n\t\tstart: Start\n\t\tpause: Pause\n\t\treset: Reset\n```"
    validations:
      require: true
