name: Translates
description: Improve code translation
title: "[TRANSLATE] Your title"
labels: ["translate"]
body:
  - type: input
    id: language
    attributes:
      label: Language
      #description:
      placeholder: eg. english
    validations:
      required: true
  - type: input
    id: lang-code
    attributes:
      label: Language code
      description: "You can find the language code at: [List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)"
      placeholder: eg. en
    validations:
      required: true
  - type: textarea
    id: translate
    attributes:
      label: Translate YAML
      description: "You can send the YAML file already translated or write it in this section.\n\n:warning: [WARNING] If you want to directly write the translation in this section, we recommend that you use the code block using YAML. You can use the \"**Preview**\" tab to see if the code has been written correctly.\n\nYou can use as a template: [en.yaml](https://github.com/BrowserSourcesForOBS/obs-timer-controller/blob/main/locales/en.json)"
      placeholder: "{\n\tkey: {\n\t\tvalue: \"The translation of the element would go here\"\n\t}\n}"
      render: json
    validations:
      required: true
